channels:
  - pyviz
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcftools
  - bleach
  - htslib
  - khmer
  - libdeflate
  - pronto
  - pyasn1-modules
  - pysam
  - samtools
  - screed
  - sourmash
  - altair
  - appdirs
  - arrow-cpp
  - atomicwrites
  - attrs
  - automat
  - backcall
  - biopython
  - bokeh
  - boost-cpp
  - boto3
  - botocore
  - bottleneck
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cftime
  - click
  - cloudpickle
  - conda
  - conda-env
  - constantly
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - dbus
  - decorator
  - distributed
  - docutils
  - entrypoints
  - expat
  - fastparquet
  - fontconfig
  - freetype
  - gettext
  - glib
  - gmp
  - gst-plugins-base
  - gstreamer
  - h5netcdf
  - h5py
  - hdf4
  - hdf5
  - heapdict
  - holoviews
  - html5lib
  - hyperlink
  - icu
  - igraph
  - ijson
  - incremental
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jmespath
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - krb5
  - libedit
  - libgfortran
  - libgfortran-ng
  - libiconv
  - libnetcdf
  - libpng
  - libsodium
  - libssh2
  - libtiff
  - libxcb
  - libxml2
  - llvmlite
  - locket
  - louvain
  - markupsafe
  - matplotlib
  - mistune
  - mkl_fft
  - mkl_random
  - mmtf-python
  - more-itertools
  - msgpack-python
  - nbconvert
  - nbformat
  - ncurses
  - netcdf4
  - notebook
  - numba
  - olefile
  - openblas
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parquet-cpp
  - parso
  - partd
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pixman
  - pluggy
  - prometheus_client
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - py
  - pyarrow
  - pyasn1
  - pycairo
  - pygments
  - pyhamcrest
  - pyparsing
  - pyqt
  - pytest
  - python
  - python-dateutil
  - python-igraph
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - reportlab
  - s3fs
  - s3transfer
  - seaborn
  - send2trash
  - service_identity
  - simplegeneric
  - sip
  - sortedcontainers
  - statsmodels
  - tblib
  - terminado
  - testpath
  - thrift
  - toolz
  - tornado
  - traitlets
  - twisted
  - ujson
  - umap-learn
  - wcwidth
  - webencodings
  - widgetsnbextension
  - xarray
  - xorg-libxau
  - xorg-libxdmcp
  - zeromq
  - zict
  - zope.interface
  - _license
  - asn1crypto
  - blas
  - bz2file
  - cffi
  - chardet
  - cryptography
  - idna
  - intel-openmp
  - libffi
  - libopenblas
  - mkl
  - numpy
  - numpy-base
  - pip
  - pycosat
  - pycparser
  - pyopenssl
  - pysocks
  - requests
  - ruamel_yaml
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - tk
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - param
  - pyviz_comms
  - pip:
    - anndata
    - joblib
    - line-profiler
    - msgpack
    - natsort
    - networkx
    - numexpr
    - py-spy
    - scanpy
    - tables
    - tqdm

